version: '3.8'
services:
  db:
    image: postgres:15
    container_name: novely_pay_db
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: novelypay
    ports:
      - '7744:5432' # Agora o "túnel" de entrada no seu Windows é 7744 # Porta do PC : Porta dentro do Docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: